In [1]:
import pandas as pd
import numpy as np

In [2]:
Rawdata = pd.read_excel('COUNTOFD_BBCO_OFT_DATABASE.xlsx', header = 0)

In [6]:
InUse = ['SKUCode', 'ReleaseDate', 'ActualDeliveryDate','DeliveryOrderVolumeHL']
df = Rawdata[InUse]
df

        SKUCode ReleaseDate ActualDeliveryDate  DeliveryOrderVolumeHL
0         62808  2021-04-23         2021-05-03                  3.200
1         78561  2021-05-20         2021-05-22                124.800
2         86774  2021-05-20         2021-05-22                 22.176
3         78561  2021-05-20         2021-05-22                115.200
4         78561  2021-05-20         2021-05-22                 43.200
5         78561  2021-05-20         2021-05-22                 14.400
6         78561  2021-05-20         2021-05-22                 19.200
7         74155  2021-05-08         2021-05-10                 27.720
8         76353  2021-05-08         2021-05-10                  3.696
9         76353  2021-05-08         2021-05-10                  4.026
10        76353  2021-05-08         2021-05-10                  4.290
11        71502  2021-05-08         2021-05-10                  6.804
12        50825  2021-05-08         2021-05-10                 11.088
13        76353  2021-05-08         2021-05-10                  6.006
14        74154  2021-05-26         2021-05-27                 82.668
15        74154  2021-05-26         2021-05-27                  5.167
16        74154  2021-05-26         2021-05-27                 25.834
17        74154  2021-05-26         2021-05-27                  5.167
18        71502  2021-04-29         2021-05-03                  1.080
19        71502  2021-04-29         2021-05-03                 26.136
20        80896  2021-04-29         2021-05-03                 18.144
21        76353  2021-04-29         2021-05-03                  4.158
22        76353  2021-04-29         2021-05-03                  2.244
23        76353  2021-04-29         2021-05-03                  5.610
24        76353  2021-04-29         2021-05-03                 24.024
25        75126  2021-05-20         2021-05-22                140.824
26        74154  2021-05-26         2021-05-27                 10.333
27        74154  2021-05-26         2021-05-27                 12.917
28        74154  2021-05-26         2021-05-27                  2.583
29        74154  2021-05-26         2021-05-27                 25.834
...         ...         ...                ...                    ...
132057    81584  2021-06-15         2021-06-16                123.552
132058    81584  2021-06-15         2021-06-16                 47.520
132059    78561  2021-06-15         2021-06-18                  0.000
132060    78561  2021-06-15         2021-06-18                  4.800
132061    78561  2021-06-15         2021-06-18                  4.800
132062    68931  2021-06-15         2021-06-19                 16.896
132063    68931  2021-06-15         2021-06-19                  0.000
132064    50825  2021-06-15         2021-06-19                  0.000
132065    50825  2021-06-15         2021-06-19                 99.792
132066    74155  2021-06-15         2021-06-16                  0.000
132067    74155  2021-06-15         2021-06-16                 27.720
132068    74155  2021-06-15         2021-06-19                  0.000
132069    74155  2021-06-15         2021-06-19                133.056
132070    50825  2021-06-15         2021-06-16                  0.000
132071    50825  2021-06-15         2021-06-16                144.144
132072    78561  2021-06-15         2021-06-17                  0.000
132073    78561  2021-06-15         2021-06-17                 52.800
132074    78561  2021-06-15         2021-06-17                 72.000
132075    78561  2021-06-15         2021-06-17                  0.000
132076    78561  2021-06-15         2021-06-17                124.800
132077    81584  2021-06-15         2021-06-17                  0.000
132078    81584  2021-06-15         2021-06-17                228.096
132079    81584  2021-06-15         2021-06-17                 19.008
132080    78561  2021-06-15         2021-06-16                  0.000
132081    78561  2021-06-15         2021-06-16                  9.600
132082    78561  2021-06-15         2021-06-16                115.200
132083    78561  2021-06-15         2021-06-16                  0.000
132084    78561  2021-06-15         2021-06-16                124.800
132085    78561  2021-06-15         2021-06-16                  0.000
132086    78561  2021-06-15         2021-06-16                124.800

[132087 rows x 4 columns]

In [9]:
group = df.groupby(['SKUCode','ReleaseDate'])['DeliveryOrderVolumeHL'].sum()

In [14]:
group

SKUCode  ReleaseDate
44946    2021-01-06       6.653
         2021-01-11       6.653
         2021-01-29      17.107
         2021-03-15      32.947
         2021-03-17      19.958
         2021-04-20      17.107
         2021-06-25       2.851
44947    2021-01-06       6.732
         2021-01-19       1.347
         2021-01-26       0.237
         2021-01-28       0.792
         2021-01-29      39.917
         2021-02-02       0.079
         2021-02-23       5.544
         2021-02-24      11.088
         2021-03-02       0.079
         2021-03-03       0.633
         2021-03-09       0.079
         2021-03-10       0.475
         2021-03-15     127.353
         2021-03-19       3.960
         2021-03-30       0.158
         2021-03-31       4.039
         2021-04-01       6.653
         2021-04-02       0.079
         2021-04-07       0.158
         2021-04-09       0.158
         2021-04-16       0.238
         2021-04-20      39.917
         2021-04-21       0.079
                         ...
89023    2021-06-23      65.520
         2021-06-24      87.360
         2021-06-28      21.840
         2021-06-29       0.060
         2021-06-30       0.060
         2021-07-01       1.560
         2021-07-02      60.060
         2021-07-05       5.460
         2021-07-09       5.460
         2021-07-13      55.800
         2021-07-14      54.600
         2021-07-15      10.920
         2021-07-16      38.220
89024    2021-06-16      12.000
         2021-06-22       0.240
         2021-06-23      65.520
         2021-06-29       0.240
         2021-06-30       0.300
         2021-07-01       9.000
         2021-07-05     131.040
         2021-07-07       0.540
         2021-07-08       9.000
         2021-07-09      54.600
         2021-07-13      12.120
89104    2021-06-01       0.900
         2021-06-10      10.800
         2021-06-29       5.400
         2021-07-01      10.800
         2021-07-05      16.200
         2021-07-16       5.400
Name: DeliveryOrderVolumeHL, Length: 8609, dtype: float64